# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sdcs_pb2 as sdcs__pb2


class CacheNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateKeyValue = channel.unary_unary(
                '/sdcs.CacheNode/UpdateKeyValue',
                request_serializer=sdcs__pb2.UpdateKeyValueRequest.SerializeToString,
                response_deserializer=sdcs__pb2.UpdateKeyValueResponse.FromString,
                )
        self.SearchKeyValue = channel.unary_unary(
                '/sdcs.CacheNode/SearchKeyValue',
                request_serializer=sdcs__pb2.SearchKeyValueRequest.SerializeToString,
                response_deserializer=sdcs__pb2.SearchKeyValueResponse.FromString,
                )
        self.DeleteKeyValue = channel.unary_unary(
                '/sdcs.CacheNode/DeleteKeyValue',
                request_serializer=sdcs__pb2.DeleteKeyValueRequest.SerializeToString,
                response_deserializer=sdcs__pb2.DeleteKeyValueResponse.FromString,
                )


class CacheNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateKeyValue(self, request, context):
        """更新kv
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKeyValue(self, request, context):
        """查询kv
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKeyValue(self, request, context):
        """删除kv
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateKeyValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKeyValue,
                    request_deserializer=sdcs__pb2.UpdateKeyValueRequest.FromString,
                    response_serializer=sdcs__pb2.UpdateKeyValueResponse.SerializeToString,
            ),
            'SearchKeyValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKeyValue,
                    request_deserializer=sdcs__pb2.SearchKeyValueRequest.FromString,
                    response_serializer=sdcs__pb2.SearchKeyValueResponse.SerializeToString,
            ),
            'DeleteKeyValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKeyValue,
                    request_deserializer=sdcs__pb2.DeleteKeyValueRequest.FromString,
                    response_serializer=sdcs__pb2.DeleteKeyValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdcs.CacheNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CacheNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateKeyValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdcs.CacheNode/UpdateKeyValue',
            sdcs__pb2.UpdateKeyValueRequest.SerializeToString,
            sdcs__pb2.UpdateKeyValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchKeyValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdcs.CacheNode/SearchKeyValue',
            sdcs__pb2.SearchKeyValueRequest.SerializeToString,
            sdcs__pb2.SearchKeyValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteKeyValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdcs.CacheNode/DeleteKeyValue',
            sdcs__pb2.DeleteKeyValueRequest.SerializeToString,
            sdcs__pb2.DeleteKeyValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
