# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\nhelloworld\"\x83\x01\n\x15UpdateKeyValueRequest\x12<\n\x06kv_map\x18\x01 \x03(\x0b\x32,.helloworld.UpdateKeyValueRequest.KvMapEntry\x1a,\n\nKvMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x16UpdateKeyValueResponse\x12\x0b\n\x03\x63nt\x18\x01 \x01(\r\"$\n\x15SearchKeyValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\'\n\x16SearchKeyValueResponse\x12\r\n\x05value\x18\x01 \x01(\t2\xc1\x01\n\tCacheNode\x12Y\n\x0eUpdateKeyValue\x12!.helloworld.UpdateKeyValueRequest\x1a\".helloworld.UpdateKeyValueResponse\"\x00\x12Y\n\x0eSearchKeyValue\x12!.helloworld.SearchKeyValueRequest\x1a\".helloworld.SearchKeyValueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _UPDATEKEYVALUEREQUEST_KVMAPENTRY._options = None
  _UPDATEKEYVALUEREQUEST_KVMAPENTRY._serialized_options = b'8\001'
  _globals['_UPDATEKEYVALUEREQUEST']._serialized_start=30
  _globals['_UPDATEKEYVALUEREQUEST']._serialized_end=161
  _globals['_UPDATEKEYVALUEREQUEST_KVMAPENTRY']._serialized_start=117
  _globals['_UPDATEKEYVALUEREQUEST_KVMAPENTRY']._serialized_end=161
  _globals['_UPDATEKEYVALUERESPONSE']._serialized_start=163
  _globals['_UPDATEKEYVALUERESPONSE']._serialized_end=200
  _globals['_SEARCHKEYVALUEREQUEST']._serialized_start=202
  _globals['_SEARCHKEYVALUEREQUEST']._serialized_end=238
  _globals['_SEARCHKEYVALUERESPONSE']._serialized_start=240
  _globals['_SEARCHKEYVALUERESPONSE']._serialized_end=279
  _globals['_CACHENODE']._serialized_start=282
  _globals['_CACHENODE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
