# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdcs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsdcs.proto\x12\x04sdcs\"*\n\x15UpdateKeyValueRequest\x12\x11\n\tkv_string\x18\x01 \x01(\t\",\n\x16UpdateKeyValueResponse\x12\x12\n\nupdate_cnt\x18\x01 \x01(\r\"$\n\x15SearchKeyValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x16SearchKeyValueResponse\x12\x11\n\tkv_string\x18\x01 \x01(\t\"$\n\x15\x44\x65leteKeyValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\",\n\x16\x44\x65leteKeyValueResponse\x12\x12\n\ndelete_cnt\x18\x01 \x01(\r2\xf8\x01\n\tCacheNode\x12M\n\x0eUpdateKeyValue\x12\x1b.sdcs.UpdateKeyValueRequest\x1a\x1c.sdcs.UpdateKeyValueResponse\"\x00\x12M\n\x0eSearchKeyValue\x12\x1b.sdcs.SearchKeyValueRequest\x1a\x1c.sdcs.SearchKeyValueResponse\"\x00\x12M\n\x0e\x44\x65leteKeyValue\x12\x1b.sdcs.DeleteKeyValueRequest\x1a\x1c.sdcs.DeleteKeyValueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdcs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATEKEYVALUEREQUEST']._serialized_start=20
  _globals['_UPDATEKEYVALUEREQUEST']._serialized_end=62
  _globals['_UPDATEKEYVALUERESPONSE']._serialized_start=64
  _globals['_UPDATEKEYVALUERESPONSE']._serialized_end=108
  _globals['_SEARCHKEYVALUEREQUEST']._serialized_start=110
  _globals['_SEARCHKEYVALUEREQUEST']._serialized_end=146
  _globals['_SEARCHKEYVALUERESPONSE']._serialized_start=148
  _globals['_SEARCHKEYVALUERESPONSE']._serialized_end=191
  _globals['_DELETEKEYVALUEREQUEST']._serialized_start=193
  _globals['_DELETEKEYVALUEREQUEST']._serialized_end=229
  _globals['_DELETEKEYVALUERESPONSE']._serialized_start=231
  _globals['_DELETEKEYVALUERESPONSE']._serialized_end=275
  _globals['_CACHENODE']._serialized_start=278
  _globals['_CACHENODE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
